Repository moul/depviz, pull requests merged in 2020-03, with the labels that each got.

#253 Elk deps fix and node-sass fix
  web/package-lock.json
  web/package.json
  web/src/components/menu/Menu.js
  web/src/components/visualizer/Visualizer.js
Labels: ✅ Approved

#248 fix: fixing missing features from web migration #245
  web/package-lock.json
  web/package.json
  web/src/components/menu/Menu.js
  web/yarn.lock
Labels: ✅ Approved

#256 fix: Superfluous attribute passing
  web/src/components/menu/Menu.js
Labels: ✅ Approved

#255 feat: configure netlify
  web/netlify.toml
  web/webpack.config.dev.js
  web/webpack.config.prod.js
Labels: help wanted, 🔍 Ready for Review

#257 fix: redraw button behavior
  web/package-lock.json
  web/src/components/menu/Menu.js
  web/src/components/menu/utils.js
  web/src/components/visualizer/Visualizer.js
Labels: ✅ Approved

#260 fix: remove duplicates
  internal/dvstore/query.go
  internal/dvstore/query_test.go
  internal/dvstore/testdata/golden.all-depviz-test_moul-and-moulbot-depviz-test.json
  internal/dvstore/testdata/golden.all-depviz-test_moul-depviz-test.json
  internal/dvstore/testdata/golden.all-depviz-test_moulbot-depviz-test.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld-with-closed.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld-without-prs.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld.json
Labels: 🔍 Ready for Review

#258 Various improvements and fixes
  web/.babelrc
  web/.env.prod
  web/.eslintignore
  web/.eslintrc.json
  web/.prettierrc
  web/README.md
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/App.scss
  web/src/api/depviz.js
  web/src/api/index.js
  web/src/assets/_variables.scss
  web/src/assets/main.scss
  web/src/components/App.js
  web/src/components/menu/Menu.js
  web/src/components/menu/index.js
  web/src/components/menu/menu.scss
  web/src/components/menu/utils.js
  web/src/components/pages/HomePage.js
  web/src/components/pages/homepage.scss
  web/src/components/visualizer/Visualizer.js
  web/src/components/visualizer/card.scss
  web/src/components/visualizer/index.js
  web/src/hooks/useStore.js
  web/src/index.ejs
  web/src/index.js
  web/src/store/index.js
  web/src/store/provider.js
  web/src/ui/Visualizer/index.js
  web/src/ui/Visualizer/renderers/Cytoscape.js
  web/src/ui/Visualizer/renderers/Mermaid.js
  web/src/ui/Visualizer/renderers/card.scss
  web/src/ui/Visualizer/renderers/cardTemplate.js
  web/src/ui/Visualizer/renderers/styles.scss
  web/src/ui/components/ErrorBoundary/ErrorBoundary.js
  web/src/ui/components/ErrorBoundary/styles.scss
  web/src/ui/components/Header/Menu.js
  web/src/ui/components/Header/styles.scss
  web/src/ui/components/Header/utils.js
  web/src/ui/components/Modal/Modal.js
  web/src/ui/components/Modal/styles.scss
  web/src/ui/pages/HomePage/HomePage.js
  web/src/ui/pages/HomePage/styles.scss
  web/src/utils/computeLayoutConfig.js
  web/src/utils/store.js
  web/src/webpack-public-path.js
  web/tools/analyzeBundle.js
  web/tools/assetsTransformer.js
  web/tools/build.js
  web/tools/chalkConfig.js
  web/tools/distServer.js
  web/tools/enzymeTestAdapterSetup.js
  web/tools/fileMock.js
  web/tools/srcServer.js
  web/tools/startMessage.js
  web/webpack.config.dev.js
  web/webpack.config.prod.js
Labels: ✅ Approved

#271 fix: bump deps
  .circleci/config.yml
  AUTHORS
  Dockerfile
  Makefile
  cmd/depviz/main.go
  gen.sum
  go.mod
  go.sum
  internal/dvstore/testing.go
  internal/githubprovider/github.go
  internal/githubprovider/model.go
  rules.mk
  tool/go.mod
  tool/go.sum
  tool/opml-to-github-issues/main.go
  tool/sed-i-github-issues/main.go
Labels: 🔍 Ready for Review

#277 feat: Ghost nodes
  .circleci/config.yml
  web/.eslintrc.json
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/api/depviz.js
  web/src/api/index.js
  web/src/index.js
  web/src/ui/Visualizer/renderers/Cytoscape.js
  web/src/ui/Visualizer/renderers/Mermaid.js
  web/src/ui/Visualizer/renderers/styles.scss
  web/src/ui/components/ErrorBoundary/ErrorBoundary.js
  web/src/ui/components/Header/Menu.js
  web/src/ui/components/Header/utils.js
  web/src/ui/components/Modal/Modal.js
  web/src/utils/store.js
  web/webpack-public-path.js
  web/webpack.config.dev.js
  web/webpack.config.prod.js
Labels: 🔍 Ready for Review

#279 Cytoscape ghost nodes
  web/package-lock.json
  web/package.json
  web/src/App.scss
  web/src/ui/Visualizer/index.js
  web/src/ui/Visualizer/renderers/Cytoscape.js
  web/src/ui/Visualizer/renderers/CytoscapeCard.js
  web/src/ui/Visualizer/renderers/Mermaid.js
  web/src/ui/Visualizer/renderers/MermaidCard.js
  web/src/ui/Visualizer/renderers/card.scss
  web/src/ui/Visualizer/renderers/cardTemplate.js
  web/src/ui/Visualizer/renderers/styles.scss
Labels: ✅ Approved
