Repository moul/depviz, pull requests merged in 2022-08, with the labels that each got.

#547 feat: add time management
  AUTHORS
  api/dvmodel.proto
  gen.sum
  go.mod
  go.sum
  internal/dvmodel/dvmodel.pb.go
  internal/githubprovider/model.go
  web/src/ui/Visualizer/renderers/GraphCard.js
  web/src/ui/Visualizer/renderers/card.scss
  web/src/ui/components/icons/Hourglass.js
Labels: enhancement, ✅ Approved

#549 feat: add assign in cards with links for each person
  web/src/ui/Visualizer/InfoBox.js
  web/src/ui/Visualizer/infoBox.scss
Labels: enhancement, 🔍 Ready for Review, web

#530 feat: add fetch repository if it not already exist in db
  internal/dvserver/api.go
Labels: enhancement, 🔍 Ready for Review

#546 chore: add github OAuth
  AUTHORS
  api/dvserver.proto
  cmd/depviz/main.go
  gen.sum
  internal/dvserver/api.go
  internal/dvserver/dvserver.pb.go
  internal/dvserver/server.go
  internal/dvstore/query.go
  internal/dvstore/testdata/golden.all-depviz-test_moul-and-moulbot-depviz-test.json
  internal/dvstore/testdata/golden.all-depviz-test_moul-depviz-test.json
  internal/dvstore/testdata/golden.all-depviz-test_moulbot-depviz-test.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld-all-flags.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld-light.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld-with-closed.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld-without-external-deps.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld-without-isolated.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld-without-prs.json
  internal/dvstore/testdata/golden.all-depviz-test_theworld.json
  web/.env.dev
  web/.env.prod
  web/src/App.js
  web/src/api/depviz.js
  web/src/ui/components/Header/Menu.js
  web/src/ui/pages/GitHubOAuthPage/GitHubOAuthPage.js
  web/yarn.lock
Labels: enhancement, 🔍 Ready for Review, web, api, chore

#559 Dev/isma/GitHub interactions
  .gitignore
  api/dvserver.proto
  internal/dvserver/api.go
  internal/dvserver/dvserver.pb.go
  internal/dvserver/dvserver.pb.gw.go
  internal/githubprovider/github.go
  web/package.json
  web/src/index.js
  web/src/ui/Visualizer/InfoBox.js
  web/src/ui/Visualizer/infoBox.scss
  web/src/ui/components/Header/Menu.js
  web/src/ui/components/Modal/Assign/Container.js
  web/src/ui/components/Modal/Assign/Form.js
  web/src/ui/components/Modal/Assign/Modal.js
  web/src/ui/components/Modal/Assign/TriggerButton.js
  web/src/ui/components/Modal/Metadata/Container.js
  web/src/ui/components/Modal/Metadata/Form.js
  web/src/ui/components/Modal/Metadata/Modal.js
  web/src/ui/components/Modal/Metadata/TriggerButton.js
  web/src/ui/components/Modal/styles.scss
  web/yarn.lock
Labels: 🔍 Ready for Review

#569 chore: fix missing deps + args in dockerfile
  Dockerfile
  web/package-lock.json
  web/package.json
  web/yarn.lock
Labels: 🔍 Ready for Review, chore
